dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas  
    - beautifulsoup4
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
